[package]
name = "raptor-cli"
version = "0.1.0"
authors = ["aspen <aspenuwu@protonmail.com>"]
edition = "2018"

[[bin]]
name = "raptor"
path = "src/main.rs"

[dependencies]
raptor = { path = "../raptor" }
rayon = "1.5.0"
structopt = "0.3.21"
sha2 = "0.9.3"
hex = "0.4.3"
